config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'portfolios#index'
  get "portfolio" => "portfolios#index"
  resources :transactions, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :symbol, presence: true, length: { in: 1..5 }
  validates :quantity,
    presence: true,
    numericality: {
      only_integer: true,
      greater_than: 0
    }
  validates :share_price, presence: true, numericality: { greater_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :get_stock_price

  def get_stock_quote(sym)
    url = "https://api.iextrading.com/1.0/stock/"
    api = config_adapter(url)
    api.get "#{sym}/quote"
  end

  def get_batch_quote(sym_arr)
    url = "https://api.iextrading.com/1.0/stock/market/batch"
    sym_arrs = sym_arr.each_slice(100).to_a
    api = config_adapter(url)
    result = {}

    sym_arrs.each do |symbols|
      resp = api.get "", { symbols: sym_arr.join(','),
                           types: "quote" }
      return nil if resp.status != 200
      result.merge!(resp.body)
    end

    result
  end

  protected

  def config_adapter(url)
    Faraday.new url do |conn|
      # conn.use Faraday::Response::RaiseError
      conn.response :json, content_type: /\bjson$/
      conn.adapter :typhoeus
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolio = get_prices(sum_holdings)
    @datatable = PortfoliosDatatable.new(portfolio: @portfolio, status_hash: @status_hash)
  end

  private

  def sum_holdings
    current_user.transactions.group(:symbol).sum(:quantity)
  end

  def get_prices(holdings_hash)
    # Check to make sure user has holdings
    return :absent if holdings_hash.empty?
    symbols = holdings_hash.keys
    data = get_batch_quote(symbols)
    # Check to make sure that all batch quote requests succeeded
    return :error if data.nil?
    @status_hash = {}

    symbols.collect do |sym|
      info = data[sym]["quote"]
      @status_hash[sym] = status(info["open"], info["latestPrice"])
      [sym,
       holdings_hash[sym],
       info["open"],
       info["latestPrice"],
       percent_difference(info["open"], info["latestPrice"])]
    end
  end

  def status(opn, curr)
    case
    when opn > curr
      -1
    when opn < curr
      1
    else
      0
    end
  end

  def percent_difference(first, second)
    diff = (second - first) / first
    diff * 100
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :sanitize_page_params, only: [:create]
  before_action :validate_params, only: [:create]

  def index
    @datatable = TransactionsDatatable.new
  end

  def create
    if @errors.length > 0
      flash[:danger] = @errors
      redirect_to portfolio_path
      return
    end

    trans = current_user.transactions.create(
      symbol: params[:stock_symbol],
      quantity: params[:qty],
      share_price: params[:share_price])

    if trans.save
      update_balance
    else
      flash[:danger] = "An unknown error occurred. " \
                       "No transaction has been made"
      redirect_to portfolio_path
      return
    end

    amt = params[:qty]
    @success = "Transaction successful. " \
               "You have bought #{amt} " \
               "share#{amt > 1 ? "s" : nil} " \
               "of #{params[:stock_symbol]} at " \
               "$#{@price} per share."

    flash[:success] = @success
    redirect_to portfolio_path
  end

  private

  def validate_params
    @errors = []

    unless validate_quantity
      @errors << "This application does not support " \
                 "the number of shares you have attempted " \
                 "to acquire."
    end

    @price = get_stock_quote(params[:stock_symbol])

    # Validate non-error state from API
    if @price.status != 200
      @errors << @price.body ? @price.body : "Server error."
      # If so, validate non-nil price value in response from API
    elsif @price.body["latestPrice"].nil?
      @errors << "An unkown error has occured."
      # If so, set @price to price from API
    else
      @price = @price.body["latestPrice"]
    end

    @frontend_price = params[:share_price]

    unless validate_price
      @errors << "#{params[:stock_symbol]} is " \
                 "no longer available at #{@frontend_price}"
    end

    unless validate_balance
      @errors << "There are insufficient funds in your account " \
                 "to complete this transaction."
    end

    if @errors.length > 0
      @errors << "No transaction has occurred. " \
                 "Please try again."
    end

    @errors
  end

  # Check to make sure that the current balance is
  # sufficient to cover the requested transaction
  def validate_balance
    current_user.balance >= transaction_total
  end

  # A lower price than expected is always valid.
  # A price that is more than 1 percent greater
  # than expected is invalid.
  def validate_price
    @price / @frontend_price * 100.0 >= 99.0
  end

  # Valid quantity must be an integer greater than 0
  # and less than postgres max int size
  def validate_quantity
    qty = params[:qty]
    qty.between?(1, 2 ** 31 - 1) && qty.is_a?(Integer)
  end

  def update_balance
    new_balance = current_user.balance - transaction_total
    current_user.update(balance: new_balance)
  end

  def transaction_params
    params.permit(:stock_symbol, :qty, :share_price)
  end

  def transaction_total
    params[:qty] * @price
  end

  def sanitize_page_params
    params[:stock_symbol] = params[:stock_symbol].upcase
    params[:qty] = params[:qty].to_i
    params[:share_price] = params[:share_price].to_f
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">

      <a class="navbar-brand mr-auto mr-lg-0" href="/portfolio">Stock Trader</a>

      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault" data-turbolinks="false">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/portfolio">Portfolio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/transactions">Transactions</a>
          </li>
          <li class="nav-item">
            <%=link_to "Log out", destroy_user_session_path, :method => :delete, :class =>"nav-link" %>
          </li>
        </ul>
      </div>
      <%# <%= javascript_include_tag('offcanvas') %>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Trader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/nav" %>
      <%= yield %>
      <div class="alert-container">
        <% unless flash.empty? %>
            <% flash.each do |key, value| %>
              <% key = "info" if key == "notice" %>
              <% key = "warning" if key == "alert" %>
              <% if value.kind_of?(Array) %>
                <% value.each do |val| %>
                  <div class="alert alert-<%= key %>"><%= val %></div>
                <% end %>
              <% else %>
                  <div class="alert alert-<%= key %>"><%= value %></div>
              <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/portfolios/_order_form.html.erb
<div id='order-form-container' class='col-lg-3 offset-lg-1'>
  <h3>Balance: 
    <span class='user-balance'>
      <%= number_to_currency(current_user.balance) %>
    </span>
  </h3>

  <%= bootstrap_form_with(url: transactions_path, id:'buy-form') do |f| %>

    <%= f.text_field :stock_symbol, id:'symbol-input',
                      label: "Stock Symbol",
                      placeholder: 'symbol', maxlength: 5, minlength: 1,
                      style: 'text-transform:uppercase',
                      required: true, spellcheck: false,
                      help: "Must be a valid stock symbol between 1 and 5 charachters long"
    %>

    <div class="form-group">
      <button class="btn btn-primary"type="button" id="price-quote-btn">
        Get Current Price Quote
      </button>
    </div>
    
    <%= f.number_field :share_price, id:'price-per-share',
                        label: "Share Price (USD)", placeholder: '',
                        readonly: true, required: true,
                        prepend: "$",
                        help: "Final price may be up to 1% greater than displayed"

    %>

    <%= f.text_field :price_timestamp, id:'price-timestamp',
                      label: "Price Update Time", placeholder: '',
                      readonly: true, required: true, value: ''
    %>

    <%= f.number_field :qty, id: 'share-qty', label: 'Quantity of Shares',
                        value: 1, min: 1, max: 2**31-1, required: true
    %>
    

    <%= f.number_field :total_price, id: 'total-price', label: 'Total Price (USD)',
                        readonly: true,  prepend: "$"
    %>

    <div class='center-btn'>
      <%= f.submit 'Purchase', id: 'purchase-submit-button', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/portfolios/_portfolio.html.erb
<div id='portfolio-container' class='col-lg-8'>
<% if @portfolio == :absent %>
  <h3>Portfolio</h3>
    <div class="jumbotron">
      <h1 class="display-4">Welcome!</h1>
      <p class="lead">You don't have any stocks in your portfolio yet. Look up a stock price quote and submit a purchase order to start building your investment portfolio.</p>
    </div>
<% elsif @portfolio == :error %>
  <div class="alert alert-danger" role="alert">
    <h1 class="display-4">Oh no!</h1>
    <p class="lead">It seems there has been an error.</p>
    <p>We're terribly sorry about this. Please refresh the page or try again in a few minutes. If this problem continues please contact support.</p>
    <div class="d-flex flex-row-reverse">
      <p class="font-weight-light">Code: BCH<%= Time.now.to_time.utc.to_i %></p>
    </div>
  </div>
<% else %>
    <%= render_datatable(@datatable, search: true, buttons: false) %>
    <%# <%= render_datatable(@datatable, search: true) %>
    <%# <%= render_datatable_charts(@datatable) %>
<% end %>
</div>

app/views/portfolios/index.html.erb
<h1><%= current_user.name %>'s Portfolio</h1>
<div class="row">
  <%= render 'portfolio' %>
  <%= render 'order_form' %>
</div>

app/views/transactions/index.html.erb
<h1><%= current_user.name %>'s Transactions</h1>
<%= render_datatable(@datatable, search: false) %>